[package]
name = "Choam"
version = "0.1.3"
description = "Python project scaffolder/manager"
repo = "https://github.com/cowboycodr/choam"
keywords = [ "package", "manager",]

[modules]
choam = "*"
toml = "*"
fire = "*"
findimports = "*"
pathlib = "*"
shutil = "*"
typing = "*"
twine = "*"
wheel = "*"
