[package]
name = "Choam"
version = "0.1.4"
description = "Python project scaffolder/manager"
repo = "https://github.com/cowboycodr/choam"
keywords = [ "package", "manager",]

[modules]
toml = "*"
fire = "*"
choam = "*"
shutil = "*"
typing = "*"
pathlib = "*"
findimports = "*"
