[package]
name = "Choam"
version = "0.1.5"
description = "Python project scaffolder/manager"
repo = "https://github.com/cowboycodr/choam"
keywords = [ "package", "manager",]

[modules-ignore]
shutil = "*"

[modules]
toml = "*"
fire = "*"
choam = "*"
typing = "*"
pathlib = "*"
importlib = "*"
findimports = "*"
