[package]
name = "Choam"
version = "0.1.16"
description = "Python project scaffolder/manager"
repo = "https://github.com/cowboycodr/choam"
keywords = [ "package", "manager",]

[modules-ignore]
shutil = "*"
pathlib = "*"
platform = "*"

[script.install-reqs] # choam run install-reqs
perspective = "."
command = "${PYTHON} -m pip install -r ${CWD}/requirements.txt"

[script.make-docs]
perspective = "docs"
command = "make html"

[modules]
fire = "*"
toml = "*"
choam = "*"
twine = "*"
wheel = "*"
typing = "*"
importlib = "*"
findimports = "*"
autoapi = "*"
