[package]
name = "Choam"
version = "0.1.2"
description = "Python project scaffolder/manager"
repo = "https://github.com/cowboycodr/choam"
keywords = [ "package", "manager",]

[modules]
fire = "*"
findimports = "*"
choam = "*"
pathlib = "*"
toml = "*"
typing = "*"
