[package]
name = "Choam"
version = "0.0.7"
description = "Python project scaffolder/manager"
repo = "https://github.com/cowboycodr/choam"
keywords = [ "package", "manager",]

[modules]
toml = "*"
subprocess = "*"
pathlib = "*"
choam = "*"
findimports = "*"
sys = "*"
os = "*"
fire = "*"
