[package]
name = "Choam"
version = "0.0.3"
description = "Python project scaffolder/manager"
repo = "https://github.com/cowboycodr/choam"
keywords = [ "package", "manager",]

[modules]
toml = "*"
twine = "*"
fire = "*"
