[package]
name = "Choam"
version = "0.1.1"
description = "Python project scaffolder/manager"
repo = "https://github.com/cowboycodr/choam"
keywords = [ "package", "manager",]

[modules]
findimports = "*"
toml = "*"
fire = "*"
pathlib = "*"
choam = "*"
typing = "*"
twine = "*"
wheel = "*"
flask = "*"
