[package]
name = "Choam"
version = "0.1.15"
description = "Python project scaffolder/manager"
repo = "https://github.com/cowboycodr/choam"
keywords = [ "package", "manager",]

[modules-ignore]
shutil = "*"
pathlib = "*"
platform = "*"

[modules]
fire = "*"
toml = "*"
choam = "*"
twine = "*"
wheel = "*"
typing = "*"
importlib = "*"
findimports = "*"
autoapi = "*"
