[package]
name = "Choam"
version = "0.1.0"
description = "Python project scaffolder/manager"
repo = "https://github.com/cowboycodr/choam"
keywords = [ "package", "manager",]

[modules]
toml = "*"
findimports = "*"
fire = "*"
typing = "*"
pathlib = "*"
choam = "*"
twine = "*"
wheel = "*"
