[package]
name = "Choam"
version = "0.1.2"
description = "Python project scaffolder/manager"
repo = "https://github.com/cowboycodr/choam"
keywords = [ "package", "manager",]

[modules]
typing = "*"
choam = "*"
findimports = "*"
fire = "*"
toml = "*"
pathlib = "*"
twine = "*"
wheel = "*"
