[package]
name = "Choam"
version = "0.0.7"
description = "Python project scaffolder/manager"
repo = "https://github.com/cowboycodr/choam"
keywords = [ "package", "manager",]

[modules]
typing = "*"
fire = "*"
findimports = "*"
toml = "*"
pkg_resources = "*"
pathlib = "*"
choam = "*"
