[package]
name = "Choam"
version = "0.1.25"
description = "Python project scaffolder/manager"
repo = "https://github.com/cowboycodr/choam"

[modules-ignore]
shutil = "*"
pathlib = "*"
platform = "*"

[modules]
fire = "*"
toml = "*"
twine = "*"
wheel = "*"
choam = "*"
typing = "*"
autoapi = "*"
findimports = "*"

[modules-dev]
black = "*"
requests = "*"
pylint = "*"

[script.install-reqs]
perspective = "."
command = "${PYTHON} -m pip install -r ${CWD}/requirements.txt"

[script.fmt]
description = "Format project files with `black`"
requires = [ "black",]
perspective = "${PROJECT}"
command = "${PYTHON} -m black ."

[script.motivation]
description = "Prints a motivational quote from zenquotes.io"
requires = [ "requests",]
perspective = ".choam${SEP}scripts${SEP}motivation"
command = "${PYTHON} get_quote.py"

[script.lint]
description = "Lint Project files with PyLint"
requires = [ "pylint",]
perspective = "."
command = "${PYTHON} -m pylint ${PROJECT}"
