[package]
name = "Choam"
version = "0.1.23"
description = "Python project scaffolder/manager"
repo = "https://github.com/cowboycodr/choam"
keywords = [ "package", "manager",]

[modules-ignore]
shutil = "*"
pathlib = "*"
platform = "*"

[modules]
fire = "*"
toml = "*"
twine = "*"
wheel = "*"
choam = "*"
typing = "*"
autoapi = "*"
findimports = "*"

[modules-dev]
black = "*"

[script.install-reqs]
perspective = "."
command = "${PYTHON} -m pip install -r ${CWD}/requirements.txt"

[script.fmt]
description = "Format project files with `black`"
requires = [ "black",]
perspective = "${PROJECT}"
command = "${PYTHON} -m black ."

[script.motivation]
description = "Prints a motivational quote retrieved with cURL"
perspective = ".choam${SEP}scripts${SEP}motivation"
command = "${PYTHON} get_quote.py"